version: '3.8'

services:
  start-page:
    container_name: malicious-pickle-start-page
    build: .
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - data:/app/data

volumes:
  data:
    name: malicious-pickle-start-page